### PR TITLE
Shell Sort In C++ Added

### PR DESCRIPTION
**Pull request by saggu10417**

### CODE REVIEW

**Comment by jenistenxavier** [comment]
@saggu10417 : It would be great if you can add the description along with the issue number.
Feel free to use our contribution guidelines (https://github.com/fnplus/interview-techdev-guide/blob/master/CONTRIBUTING.md#how-to-contribute-an-implementation-code) for reference

**Comment by jenistenxavier** [comment]
Check the following section to know more about contributing PR's linked to issues. https://github.com/fnplus/interview-techdev-guide/blob/master/CONTRIBUTING.md#how-to-contribute-an-implementation-code

**Comment by saggu10417** [comment]
@jenistenxavier okay I'll do this.

**Comment by xlogix** [comment]
Thanks for contributing!

**Pull request merged**
