### PR TITLE
Added other code for dfs in python

### PR DESCRIPTION
**Pull request by dheeraj-2000**
I will like to add another code for Depth First Search in Python

### CODE REVIEW

**Comment by jenistenxavier** [comment]
@dheeraj-2000 : It would be great if you can add the description along with the issue number.
Feel free to use our contribution guidelines (https://github.com/fnplus/interview-techdev-guide/blob/master/CONTRIBUTING.md#how-to-contribute-an-implementation-code) for reference

**Comment by jenistenxavier** [comment]
@dheeraj-2000 : Hope you have added your PR number. We meant to link this PR to an issue. Check the following section to know more about contributing PR's linked to issues. https://github.com/fnplus/interview-techdev-guide/blob/master/CONTRIBUTING.md#how-to-contribute-an-implementation-code

**Comment by jenistenxavier** [comment]
https://github.com/fnplus/interview-techdev-guide/pull/226 is your PR number 
Please assing the PR to an issue.




Check the following section to know more about contributing PR's linked to issues. https://github.com/fnplus/interview-techdev-guide/blob/master/CONTRIBUTING.md#how-to-contribute-an-implementation-code

**Comment by dheeraj-2000** [comment]
@jenistenxavier Please refer to the Issue #444 for this #226  Pull Request no.

**Comment by jenistenxavier** [comment]
: Thanks for Contributing

**Pull request merged**
