### PR TITLE
Add selectionsort.cpp 

### PR DESCRIPTION
**Pull request by kmalik31**
selectionsort.cpp Add Selection Sort Algorithm
This adds an Selection Sort Algorithm which returns an Sorted Array 
in O(n^2) Time Complexity.
Closes - #224

### CODE REVIEW

**Comment by jenistenxavier** [comment]
@kmalik31 : It would be great if you can add the description along with the issue number.
Feel free to use our contribution guidelines (https://github.com/fnplus/interview-techdev-guide/blob/master/CONTRIBUTING.md#how-to-contribute-an-implementation-code) for reference

**Comment by kmalik31** [comment]
is that good or more changes are needed? @jenistenxavier

**Comment by jenistenxavier** [comment]
https://github.com/fnplus/interview-techdev-guide/pull/224  
is your PR number 
Please assing the PR to an issue.

**Comment by jenistenxavier** [comment]
Check the following section to know more about contributing PR's linked to issues. https://github.com/fnplus/interview-techdev-guide/blob/master/CONTRIBUTING.md#how-to-contribute-an-implementation-code

**Comment by xlogix** [comment]
Thanks for contributing!

**Pull request merged**
