### PR TITLE
COMPUTATIONAL GEOMETRY

### PR DESCRIPTION
**Pull request by siddharthrajaraja**
Basically in this algorithm two end points of two line segments are taken and it checks whether the two line segments intersects or not!!

### CODE REVIEW

**Comment by siddharthrajaraja** [comment]
Sieve of Erastosthenes too done in the same please verify

**Comment by siddharthrajaraja** [comment]
Did u see my Code?

**Comment by jenistenxavier** [comment]
@siddharthrajaraja : It would be great if you can add the description along with the issue number.
Feel free to use our contribution guidelines (https://github.com/fnplus/interview-techdev-guide/blob/master/CONTRIBUTING.md#how-to-contribute-an-implementation-code) for reference

**Comment by jenistenxavier** [comment]
@siddharthrajaraja :  Thanks for Contributing, Can you create a folder inside Algorithms and move you files into that folder

**Comment by jenistenxavier** [comment]
Issue - https://github.com/fnplus/interview-techdev-guide/issues/270

**Comment by jenistenxavier** [comment]
@xlogix :
Merging the PR for now. 
We'l reorganise his files to folders later.

**Pull request merged**
