### PR TITLE
Added Make Change

### PR DESCRIPTION
**Pull request by Devamjoshi3**
Solves Issue #442 
Matrix Chain Multiplication
Make Change

### CODE REVIEW

**Comment by xlogix** [comment]
It would be great if you can add the description along with the issue number.
Feel free to use our contribution guidelines (https://github.com/fnplus/interview-techdev-guide/blob/master/CONTRIBUTING.md#how-to-contribute-an-implementation-code) for reference

**Comment by xlogix** [comment]
Please add an issue number to the PR.

**Comment by Devamjoshi3** [comment]
Added Issue no.

**Comment by xlogix** [comment]
Thanks for contributing!

**Pull request merged**
