### PR TITLE
[Data Structure] Singly Linked List [Python]

### PR DESCRIPTION
**Pull request by Aditya2603**
#122 
 Creating a simple linked list in python with three nodes, traversing the created list and print the data of each node.

### CODE REVIEW

**Comment by jenistenxavier** [comment]
@Aditya2603  : Hope you have added your PR number. We meant to link this PR to an issue. Check the following section to know more about contributing PR's linked to issues. https://github.com/fnplus/interview-techdev-guide/blob/master/CONTRIBUTING.md#how-to-contribute-an-implementation-code

**Comment by jenistenxavier** [comment]
https://github.com/fnplus/interview-techdev-guide/pull/202 is your PR number 
Please assing the PR to an issue.

**Comment by Aditya2603** [comment]
#122

**Comment by xlogix** [comment]
Thanks for contributing!

**Pull request merged**
