### PR TITLE
insertion.py added.

### PR DESCRIPTION
**Pull request by giTan7**
just ive written python code for insertion sort.
[Algo/Data Structure] Insertion Sort[Python]
Issue #346

Description: Insertion Sort Algorithm is implemented in Python.

### CODE REVIEW

**Comment by jenistenxavier** [comment]
@giTan7 It would be great if you can add the description along with the issue number.
Feel free to use our contribution guidelines (https://github.com/fnplus/interview-techdev-guide/blob/master/CONTRIBUTING.md) for reference

**Comment by giTan7** [comment]
[Algo/Data Structure] Insertion Sort[Python]
Issue #346

I guess, this is required?

**Comment by jenistenxavier** [comment]
https://github.com/fnplus/interview-techdev-guide/pull/346 : Hope you have added your PR number. We meant to link this PR to an issue. Check the following section to know more about contributing PR's linked to issues. https://github.com/fnplus/interview-techdev-guide/blob/master/CONTRIBUTING.md#how-to-contribute-an-implementation-code

**Comment by xlogix** [comment]
Thanks for contributing!

**Comment by giTan7** [comment]
Welcome.

**Pull request merged**
