### PR TITLE
Added insertion sort in C, Python and selection in C

### PR DESCRIPTION
**Pull request by pranav6670**
For issue #108

### CODE REVIEW

**Comment by jenistenxavier** [comment]
@pranav6670 :  Thanks for contributing. It would be great if you can add the description along with the issue number.
Feel free to use our contribution guidelines (https://github.com/fnplus/interview-techdev-guide/blob/master/CONTRIBUTING.md) for reference

**Comment by pranav6670** [comment]
Please check that I have done the specified task(i.e description with the issue number) or I have to open new PR?

**Comment by xlogix** [comment]
The issue has been closed. You should try adding another issue and make sure you follow one issue per PR rule.

**Comment by jenistenxavier** [comment]
@pranav6670 : Hope you have added your PR number. We meant to link this PR to an issue. Check the following section to know more about contributing PR's linked to issues. https://github.com/fnplus/interview-techdev-guide/blob/master/CONTRIBUTING.md#how-to-contribute-an-implementation-code

**Comment by jenistenxavier** [comment]
@pranav6670 : This branch has conflicts that must be resolved before we review the PR. 
Please resolve the conflicts and submit for review. Thanks.

**Comment by xlogix** [comment]
Thanks for contributing!

**Pull request merged**
