### PR TITLE
[Data Structure] Stack Implementation [Python]

### PR DESCRIPTION
**Pull request by Aditya2603**
#157
List append() and pop() functions to create into Stack implementation class in python

### CODE REVIEW

**Comment by jenistenxavier** [comment]
@Aditya2603 : It would be great if you can add the description along with the issue number.
Feel free to use our contribution guidelines (https://github.com/fnplus/interview-techdev-guide/blob/master/CONTRIBUTING.md) for reference

**Comment by jenistenxavier** [comment]
Hope you have added your PR number. We meant to link this PR to an issue. Check the following section to know more about contributing PR's linked to issues. https://github.com/fnplus/interview-techdev-guide/blob/master/CONTRIBUTING.md#how-to-contribute-an-implementation-code

**Comment by jenistenxavier** [comment]
https://github.com/fnplus/interview-techdev-guide/pull/197 is your PR number 
Please assing the PR to an issue.

**Comment by xlogix** [comment]
Thanks for contributing!

**Pull request merged**
