### PR TITLE
added base conversion program in c

### PR DESCRIPTION
**Pull request by abhijitmanatkar**
added program to convert number from one base to another

### CODE REVIEW

**Comment by jenistenxavier** [comment]
@abhijitmanatkar : It would be great if you can add the description along with the issue number.
Feel free to use our contribution guidelines (https://github.com/fnplus/interview-techdev-guide/blob/master/CONTRIBUTING.md#how-to-contribute-an-implementation-code) for reference

**Comment by abhijitmanatkar** [comment]
Added a description along with issue number in commit message.

**Comment by jenistenxavier** [comment]
issue - https://github.com/fnplus/interview-techdev-guide/issues/251

**Comment by jenistenxavier** [comment]
thanks for contributing

**Pull request merged**
