### PR TITLE
Palindrome for a sentence

### PR DESCRIPTION
**Pull request by TharinduMD**
Palindrome.java:  Add Palindrome Algorithm

create palindrome algorithm to check a sentence is palindrome or not. Uppercase and lowercase letters also can add and white spaces also have in this sentence. If the sentence is palindrome or not massage get relevant to it.

Closes https://github.com/fnplus/interview-techdev-guide/issues/150

### CODE REVIEW

**Comment by jenistenxavier** [comment]
@TharinduMD : It would be great if you can add the description along with the issue number.
Feel free to use our contribution guidelines (https://github.com/fnplus/interview-techdev-guide/blob/master/CONTRIBUTING.md) for reference

**Comment by TharinduMD** [comment]
Added the issue number

**Comment by TharinduMD** [comment]
@jenistenxavier : can you review again?

**Comment by jenistenxavier** [comment]
@TharinduMD : Thanks for Contributing.  Can you please move your files to existing folder locations.

**Comment by jenistenxavier** [comment]
Thanks for contributing

**Pull request merged**
