### PR TITLE
feat(DataStructure): Add C Stack

### PR DESCRIPTION
**Pull request by RafaelGSS**
Ref: #10

### CODE REVIEW

**Comment by sauravjaiswalsj** [comment]
Thanks for contributing. But it would be great if you could add description along with the issue number.

**Comment by RafaelGSS** [comment]
Done! @sauravjaiswalsj

**Comment by RafaelGSS** [comment]
Another PR that was written after this one was first dipped. Maybe another stack2.c file?

**Comment by sauravjaiswalsj** [comment]
This branch has conflicts that must be resolved. Please, resolve the issue.

**Comment by sauravjaiswalsj** [comment]
Thanks for contributing

**Pull request merged**
