### PR TITLE
c++ program to check armstrong number

### PR DESCRIPTION
**Pull request by amul123**
#245

### CODE REVIEW

**Comment by jenistenxavier** [comment]
@amul123 : Hope you have added your PR number. We meant to link this PR to an issue. Check the following section to know more about contributing PR's linked to issues. https://github.com/fnplus/interview-techdev-guide/blob/master/CONTRIBUTING.md#how-to-contribute-an-implementation-code

**Comment by jenistenxavier** [comment]
Also please moved your algorithm to the appropriate folder location

**Comment by amul123** [comment]
i have placed the file in correct folder. issue number #247

**Comment by amul123** [comment]
sir please look at my other pull requests too..  #294  #262 #253 #258

**Comment by jenistenxavier** [comment]
@amul123 : There are two commits in you PR https://github.com/fnplus/interview-techdev-guide/pull/247. and you have added a new file e7712f818ff573d96e3013e9550907611f7844d0 with the right folder location instead of editing the old commit 712a6b0f44e635983742acc7e84f81c28179d992.

Delete the file in your first commit 712a6b0f44e635983742acc7e84f81c28179d992

**Pull request merged**
