### PR TITLE
heapsort

### PR DESCRIPTION
**Pull request by arun-aditya**
Added a c code for heapsort

### CODE REVIEW

**Comment by jenistenxavier** [comment]
@arun-aditya : It would be great if you can add the description along with the issue number.
Feel free to use our contribution guidelines (https://github.com/fnplus/interview-techdev-guide/blob/master/CONTRIBUTING.md) for reference

**Comment by arun-aditya** [comment]
Hi i have done the necessary.

**Comment by jenistenxavier** [comment]
@arun-aditya :  Please check out our guidelines (https://github.com/fnplus/interview-techdev-guide/blob/master/CONTRIBUTING.md) for submitting PR

**Comment by jenistenxavier** [comment]
You may have to add the issue number when sending the PR

**Comment by arun-aditya** [comment]
I will do the necessary😊.

**Comment by xlogix** [comment]
Thanks for contributing!

**Pull request merged**
