### PR TITLE
Worked on [Algorithm] Euclidean GCD [C] #144

### PR DESCRIPTION
**Pull request by Rahul-45**
Completed Euclidean GCD in C

### CODE REVIEW

**Comment by sauravjaiswalsj** [comment]
Thanks for contributing. But can you please add the issue number in your description.

**Comment by Rahul-45** [comment]
Sure will do

**Comment by Rahul-45** [comment]
Done

**Comment by sauravjaiswalsj** [comment]
I can not find the issue number. Check the issue section for help.

**Comment by sauravjaiswalsj** [comment]
closing #144

**Comment by sauravjaiswalsj** [comment]
Thanks for contributing.

**Pull request merged**
