### PR TITLE
Shell sort

### PR DESCRIPTION
**Pull request by amul123**
#250

### CODE REVIEW

**Comment by amul123** [comment]
i have corrected the location of my file. please merge it.

**Comment by jenistenxavier** [comment]
@amul123 Issues mentioned here has to be fixed before merging the PR

https://github.com/fnplus/interview-techdev-guide/pull/247#issuecomment-538807629

**Comment by amul123** [comment]
@jenistenxavier  done.. deleted  the file

**Comment by xlogix** [comment]
Thanks for contributing!

**Pull request merged**
