### PR TITLE
added findHeight.cpp

### PR DESCRIPTION
**Pull request by bedant**

### CODE REVIEW

**Comment by jenistenxavier** [comment]
@bedant : It would be great if you can add the description along with the issue number.
Feel free to use our contribution guidelines (https://github.com/fnplus/interview-techdev-guide/blob/master/CONTRIBUTING.md#how-to-contribute-an-implementation-code) for reference

**Comment by jenistenxavier** [comment]
Check the following section to know more about contributing PR's linked to issues. https://github.com/fnplus/interview-techdev-guide/blob/master/CONTRIBUTING.md#how-to-contribute-an-implementation-code

**Comment by jenistenxavier** [comment]
There are conflicts wih you PR. Could you resolve them and let us know. We'l review the PR again. 
Thanks

**Comment by xlogix** [comment]
Thanks for contributing!

**Pull request merged**
