### PR TITLE
[Algo] Perfect Number [C]

### PR DESCRIPTION
**Pull request by Aditya2603**
#133
Program that checks the  given number is perfect number or not in c language.

### CODE REVIEW

**Comment by jenistenxavier** [comment]
@Aditya2603 : It would be great if you can add the description along with the issue number.
Feel free to use our contribution guidelines (https://github.com/fnplus/interview-techdev-guide/blob/master/CONTRIBUTING.md) for reference

**Comment by jenistenxavier** [comment]
@Aditya2603 : Hope you have added your PR number. We meant to link this PR to an issue. 
Check the following section to know more about contributing PR's linked to issues. 
https://github.com/fnplus/interview-techdev-guide/blob/master/CONTRIBUTING.md#how-to-contribute-an-implementation-code

**Comment by jenistenxavier** [comment]
https://github.com/fnplus/interview-techdev-guide/pull/201 is your PR number 
Please assing the PR to an issue.

**Comment by xlogix** [comment]
Thanks for contributing!

**Pull request merged**
