### PR TITLE
Queue in ruby

### PR DESCRIPTION
**Pull request by AnkDos**
Queue in ruby !

### CODE REVIEW

**Comment by jenistenxavier** [comment]
@AnkDos : It would be great if you can add the description along with the issue number.
Feel free to use our contribution guidelines (https://github.com/fnplus/interview-techdev-guide/blob/master/CONTRIBUTING.md) for reference

**Comment by AnkDos** [comment]
Hi I have added the required description .

**Comment by jenistenxavier** [comment]
@AnkDos : You have to link the PR to an issue. Check this out 
https://github.com/fnplus/interview-techdev-guide/blob/master/CONTRIBUTING.md#how-to-contribute-an-implementation-code

**Comment by xlogix** [comment]
Thanks for contributing!

**Pull request merged**
