### PR TITLE
[Algorithm] Fibonacci [JAVA]

### PR DESCRIPTION
**Pull request by viveksdf**
This code represents the fibonacci series for example, 1,1,2,3,5...............

### CODE REVIEW

**Comment by jenistenxavier** [comment]
> _No description provided._

@viveksdf : It would be great if you can add the description along with the issue number.
Feel free to use our contribution guidelines (https://github.com/fnplus/interview-techdev-guide/blob/master/CONTRIBUTING.md) for reference

**Comment by jenistenxavier** [comment]
@viveksdf  : Please resolve the conflicts and submit for review. Thanks.

**Comment by viveksdf** [comment]
Done

**Comment by xlogix** [comment]
Thanks for contributing!

**Pull request merged**
